version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

  backend:
    image: proyectofinal-backend
    depends_on:
      - mongo
      - redis
    ports:
      - "5000:5000"

  chat:
    build:
      context: ./BackJs
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "4000:4000"

volumes:
  mongo-data:
